"""Achievement event-normalized ("zoomed") metric plots.

For each achievement that has a known first-unlock checkpoint, these functions
slice the metric timeseries into a ±W checkpoint window centred on that unlock
event, normalize the x-axis so x=0 is the first-unlock checkpoint, and overlay
all achievements on a single figure.

This reveals how metrics change in the neighbourhood of each achievement being
first encountered in evaluation — allowing comparison across achievements with
different unlock timings.
"""
from __future__ import annotations

import os

import matplotlib.pyplot as plt
import numpy as np

from graphing.loader import RunData
from graphing.styles import (
    apply_base_style, save_fig, ACHIEVEMENT_COLORS,
)

# Metrics for which zoomed plots are generated by default
DEFAULT_ZOOM_METRICS = [
    "opposition_score",
    "coherence_success",
    "coherence_failure",
    "activation_separation",
    "activation_cosine_distance",
]

_YLABEL: dict[str, str] = {
    "opposition_score":           "Cosine similarity (success vs failure gradients)",
    "coherence_success":          "Gradient coherence — success group",
    "coherence_failure":          "Gradient coherence — failure group",
    "gradient_magnitude_success": "Gradient magnitude — success group",
    "gradient_magnitude_failure": "Gradient magnitude — failure group",
    "activation_separation":      "Activation centroid separation (Euclidean)",
    "activation_cosine_distance": "Activation cosine distance",
}


def plot_zoomed(
    run_data: RunData,
    metric: str,
    window_checkpoints: int = 5,
    output_dir: str = "graphs/",
    dpi: int = 150,
) -> str | None:
    """Plot metric in a ±window_checkpoints window around each achievement's first unlock.

    All achievements are overlaid on a single figure. X-axis is in checkpoint
    index units (not training steps), centred at 0 = first-unlock checkpoint.
    A vertical dashed line marks x=0.

    Args:
        run_data:            Loaded RunData (must have achievement_first_steps populated)
        metric:              Metric key, e.g. "opposition_score"
        window_checkpoints:  Half-width of the window in number of checkpoints (default 5)
        output_dir:          Directory for saved PDF
        dpi:                 Figure DPI

    Returns:
        Saved file path, or None if no achievement has a known first-unlock step
        or the metric has no data.
    """
    if not run_data.achievement_first_steps:
        return None

    y_all = np.array(run_data.metrics.get(metric, []), dtype=float)
    if not np.isfinite(y_all).any():
        return None

    steps = run_data.steps
    W = window_checkpoints
    n = len(steps)

    fig, ax = plt.subplots(figsize=(10, 5))

    plotted = 0
    for idx, (label, first_step) in enumerate(
            sorted(run_data.achievement_first_steps.items())):
        # Find the index in steps closest to the first-unlock step
        diffs = [abs(s - first_step) for s in steps]
        center_idx = int(np.argmin(diffs))

        # Slice indices: pad with NaN outside the available range
        x_rel = list(range(-W, W + 1))
        y_window = []
        for offset in range(-W, W + 1):
            si = center_idx + offset
            if 0 <= si < n:
                y_window.append(y_all[si])
            else:
                y_window.append(float("nan"))

        y_window = np.array(y_window, dtype=float)
        if not np.isfinite(y_window).any():
            continue

        color = ACHIEVEMENT_COLORS[idx % len(ACHIEVEMENT_COLORS)]
        ax.plot(x_rel, y_window, color=color, label=label, linewidth=1.4, alpha=0.85)
        plotted += 1

    if plotted == 0:
        plt.close(fig)
        return None

    ax.axvline(0, color="black", lw=1.2, linestyle="--", alpha=0.7, label="First unlock")
    ax.set_xlabel("Checkpoints relative to first achievement unlock")
    ax.set_ylabel(_YLABEL.get(metric, metric))
    ax.set_title(f"Zoomed: {metric.replace('_', ' ').title()} around achievement unlock")
    ax.set_xticks(range(-W, W + 1))
    apply_base_style(ax)

    # Legend: two columns outside the plot if many achievements
    ncol = max(1, min(3, plotted // 6 + 1))
    ax.legend(fontsize=8, loc="upper center", bbox_to_anchor=(0.5, -0.18),
              ncol=ncol, frameon=True)
    fig.subplots_adjust(bottom=0.25)

    safe_name = metric.replace(" ", "_")
    path = save_fig(fig, os.path.join(output_dir, f"zoomed_{safe_name}.pdf"), dpi)
    return path


def plot_zoomed_all_metrics(
    run_data: RunData,
    output_dir: str = "graphs/",
    window_checkpoints: int = 5,
    dpi: int = 150,
    metrics: list[str] | None = None,
) -> list[str]:
    """Generate zoomed plots for all default (or specified) metrics.

    Args:
        run_data:            Loaded RunData
        output_dir:          Directory for saved PDFs
        window_checkpoints:  Half-width of each window
        dpi:                 Figure DPI
        metrics:             List of metric keys; defaults to DEFAULT_ZOOM_METRICS

    Returns:
        List of saved file paths.
    """
    if metrics is None:
        metrics = DEFAULT_ZOOM_METRICS
    saved = []
    for m in metrics:
        p = plot_zoomed(run_data, m, window_checkpoints, output_dir, dpi)
        if p:
            saved.append(p)
    return saved
